name: Update UltraCompare Chocolatey Package

on:
  schedule:
  - cron: '0 2 * * *'
  workflow_dispatch:


permissions:
  contents: write

jobs:
  update:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install AU module
      shell: pwsh
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope Process -Force
        Install-Module -Name AU -Force -Scope CurrentUser

    - name: Run update.ps1
      id: updater
      shell: pwsh
      run: |
        Push-Location ultracompare
        .\update.ps1
        Pop-Location

    - name: Detect if package changed
      id: detect
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_ENV
        else
          echo "changed=true" >> $GITHUB_ENV
        fi

    - name: Commit version bump
      if: env.changed == 'true'
      shell: pwsh
      run: |
        git config user.name  'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "chore: bump UltraCompare to new version"
        git push

    - name: Pack Chocolatey package
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: pack ./ultracompare/ultracompare.nuspec

    - name: Chocolatey push (what-if)
      if: env.changed == 'true'
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: >
          push ultracompare/ultracompare.*.nupkg --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCOLATEY_API_KEY }} --what-if

    - name: Chocolatey push (real)
      if: env.changed == 'true' && github.event_name == 'workflow_dispatch'
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: >
          push ultracompare/ultracompare.*.nupkg --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCOLATEY_API_KEY }}
